### ISSUE TITLE
 Proposing some more low priority quality of life features

### ISSUE THREAD

**Issue by madushan1000** [josh-berry/tab-stash#382]
### Problem Statement

I'm proposing a few more features so it's easier to use tab stash as a bookmark manager. 

### Preferred Solution(s)

- [ ] An option to do nothing after tab has been stashed(right now have to pick between hide tab, unload tab, close tab).
- [x] ~~Create new empty groups from sidebar(right now have to stash at least one tab and then rename the group).~~ (already exist in "unstashed tabs" section toolbar  
- [ ] An option to stack tab groups  vertically in `stash-list.html`. right now they're stacked side by side.

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by madushan1000** [comment]
For the last feature, I realize commenting out [this line](https://github.com/josh-berry/tab-stash/blob/master/styles/view-tab.less#L14) is enough. But I don't know enough vue to make a POC.

**Comment by josh-berry** [comment]
Thanks for the feature requests! For stacking tabs vertically in the tab UI, I think #328 is trying to solve a similar problem (it probably needs a better title, since it's nearly-impossible to find; check out the comments in that issue to understand what I mean).

Re. "do nothing after stashing", I think something like #339 is probably how this would be handled (similar to Cmd+Click or Alt/Option+Click in the UI), so you can at different times decide you want to keep or close the tab, without having to mess around in the options.

Given that both of these are already covered by other issues, I'll go ahead and mark this as a duplicate, but feel free to add your thoughts to those issues!

**Comment by madushan1000** [comment]
Looks like https://github.com/josh-berry/tab-stash/issues/328 is about stacking tabs inside a tab group? I want to stack tab groups themselves in `stash-list.html`. It already happens when the screen size is small. something like this.
![image](https://github.com/josh-berry/tab-stash/assets/4597144/c630a83f-ebb7-4656-a794-3a7a05cac678)

https://github.com/josh-berry/tab-stash/issues/339 sounds perfect with an option to not close or unload the tabs.

**Comment by josh-berry** [comment]
> Looks like #328 is about stacking tabs inside a tab group? I want to stack tab groups themselves in `stash-list.html`. It already happens when the screen size is small. something like this.

Check out this comment, specifically: https://github.com/josh-berry/tab-stash/issues/328#issuecomment-1416888394

**Comment by madushan1000** [comment]
Okay, I see what you mean. I'll wait until it's implemented and see if it matches what I had in mind. For now I figured out how to do it by overriding some css. 
 
One more thing I noticed is that there is no way to set `stash-list.html` as my new tab page(not home page) because firefox doesn't let me set a custom url there.  Extensions can define a custom new tab page by adding bellow to the manifest.
```json
"chrome_url_overrides" : {
  "newtab": "stash-list.html"
}
```
